[package]
name = "parasail-sys-arm"
version = "0.3.0"
authors = ["Adam Perry <adam.n.perry@gmail.com>"]
links = "parasail"
build = "build.rs"
license = "MIT"
documentation = "https://dikaiosune.github.io/parasailors"
repository = "https://github.com/dikaiosune/parasailors"
keywords = ["simd", "bioinformatics", "sequence", "alignment"]
description = "Native bindings for ARM cpu to the parasail pairwise genetic sequence alignment library."

[dependencies]
libc = "0.2"
